### ISSUE TITLE
faftools has python3-only code

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/faftools#25]
Just making a note here, everything seems to work anyway, but installing faftools in Miniconda's Python 2.7.13 causes this error message:

```
Extracting faftools-0.1-py2.7.egg to c:\users\luke\miniconda2\envs\fafclient\lib\site-packages
  File "c:\users\luke\miniconda2\envs\fafclient\lib\site-packages\faftools-0.1-py2.7.egg\faf\api\async_client\async_client.py", line 10
    async def get(self, url, **kwargs):
            ^
SyntaxError: invalid syntax
```

As long as everything works anyway nothing needs to be done I guess.

**Comment by Brutus5000** [comment]
Is this still relevant with the python client moving to python 3?

**Comment by Wesmania** [comment]
Client isn't even using faftools anymore, so it's not. Maybe they can even be folded into server repo altogether?

**Comment by Brutus5000** [comment]
Server and python-api are still using it as of now. Can be merged once python-api is fully replaced.
