### ISSUE TITLE
Differentiate connection messages in game lobby

### ISSUE THREAD

**Issue by micheljung** [FAForever/faftools#3]
All those "Connecting to XYZ established" and similar messages make it really hard to find actual chat messages in the in-game lobby chat.

Maybe we could either colorize these messages so that they are easily distinguishable, or we could separate those messages from the chat window.

**Comment by Sheeo** [comment]
Should be filed at FAForever/fa, also a potential suggestion for https://github.com/FAForever/fa/issues/388
